### ISSUE TITLE
Send prospectus to potential sponsors

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#1]

**Comment by rowlandm** [comment]
[Link to email template](https://docs.google.com/document/d/1_mZHkE9BJsPS4jpV1Tw1NJZrO1Yl7uM1_x0IFZzDxRo/edit?usp=drivesdk)

Have to clean up later

**Comment by rowlandm** [comment]
[Link to the prospectus](https://www.canva.com/design/DAFgNiytNoM/MS6kcDsViBWSb-dwz2-GQA/view?utm_content=DAFgNiytNoM&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)

**Comment by rowlandm** [comment]
Do we need to change our theme?

**Comment by rowlandm** [comment]
Can we ask Pradeep to put the prospectus on the new website? Will it be similar - a 2023 version that is just one page?

**Comment by rowlandm** [comment]
Have to email Tom Honeyman for ARDC, Anita Kaye for Google, Someone from NCI

**Comment by rowlandm** [comment]
Someone from Pawsey, Someone from AWS.

**Comment by rowlandm** [comment]
Need to ask ARDC for free Zoom conference tool

**Comment by rowlandm** [comment]
I received an informal email from Tom and was able to negotiate our first key partner for 2023.


Rowland Mosbergen <rowland.h.mosbergen@gmail.com>
Attachments
5:29 PM (0 minutes ago)
to Mark, Tom

Hi Mark,

Good news! Tom and the ARDC have agreed to be a key partner for us again this year!

Could we provide an invoice for the ARDC through Tom please?

It would be a similar invoice to last year as the amounts have stayed the same.

Regards,

**Comment by rowlandm** [comment]
---------- Forwarded message ---------
From: Tom Honeyman <tom.honeyman@ardc.edu.au>
Date: Fri, May 19, 2023 at 5:33 PM
Subject: Re: Invoice for Key Partnership from ARDC
To: Rowland Mosbergen <rowland.h.mosbergen@gmail.com>
Cc: Mark Crowe <mark.crowe@qcif.edu.au>, Andrew Treloar <andrew.treloar@ardc.edu.au>, Carmel Walsh <carmel.walsh@ardc.edu.au>


Hi Mark,

Yes, just confirming (with Andrew and Carmel CC'ed in) that we're very happy to proceed with supporting the RSE Unconference again this year as a "key partner".

Kind regards,
Tom

On Fri, May 19, 2023 at 5:30 PM Rowland Mosbergen <rowland.h.mosbergen@gmail.com> wrote:
Hi Mark,

Good news! Tom and the ARDC have agreed to be a key partner for us again this year!

Could we provide an invoice for the ARDC through Tom please?

It would be a similar invoice to last year as the amounts have stayed the same.

Regards,

**Comment by rowlandm** [comment]
[Updated RSEAA#0067](https://docs.google.com/document/d/1_mZHkE9BJsPS4jpV1Tw1NJZrO1Yl7uM1_x0IFZzDxRo/edit?usp=sharing) - can we please review by[ Tuesday Australian morning time please](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230522T2100)? 

@sapkota-subash @SaranjeetKaur @GraceAHall @kozo2 @pr4deepr @Emmanuel19-ada @lessa-maker @shyamaW

**Comment by rowlandm** [comment]
Here is an example of a sponsor letter to AAL using Research Software Engineer Asia Australia as the conference and changing it to be online from 13 to 15 September:

Subject: Sponsorship request for the Research Software Engineer Asia Australia Conference 2023

Dear AAL,

I am writing to you on behalf of the Research Software Engineers Association of Australia and New Zealand (RSE-AUNZ), the peak body for research software engineers in the region. We are organising the Research Software Engineer Asia Australia Conference 2023, which will be held online from 13 to 15 September 2023. The conference is the first and largest event for research software engineers in Asia and Australia, attracting over 300 participants from academia, industry, and government.

The conference will feature keynote speakers, plenary sessions, parallel sessions, poster presentations, workshops, and hackathons. The conference will showcase the latest developments and best practices in research software engineering, as well as the impact and benefits of research software for science, society, and innovation. The conference will also provide a platform for networking, collaboration, and mentoring among research software engineers at all career stages.

We are seeking sponsorship from AAL to support the conference and help us achieve our goals of promoting excellence, diversity, and inclusion in research software engineering. As a sponsor, you will receive:

- Logo placement and recognition on the conference website, program, and signage
- A complimentary virtual exhibition booth at the conference platform
- Two complimentary registrations for the conference
- An opportunity to present a sponsored talk or workshop at the conference
- An invitation to the conference social events
- A certificate of appreciation and a thank-you letter

We are requesting a sponsorship amount of $10,000 from AAL. This amount will help us cover the costs of platform fees, speaker fees, and student scholarships. We believe that your sponsorship will be a valuable investment for AAL, as it will demonstrate your commitment and leadership in supporting research software engineering and enhancing its visibility and reputation.

We would be delighted to have AAL as a sponsor for the Research Software Engineer Asia Australia Conference 2023. Please let us know if you are interested in this opportunity by 31 July 2023. We can provide you with more details and a sponsorship agreement upon your confirmation.

Thank you for your time and consideration. We look forward to hearing from you soon.

Sincerely,

Dr John Lee
President of the Research Software Engineers Association of Australia and New Zealand
Email: john.lee@rse.org.au
Phone: 0400 000 000

**Comment by rowlandm** [comment]
Email using my WEHI account.

**Comment by rowlandm** [comment]
Ask the CTO of Pawsey who the best person would be to ask about sponsorship at Pawsey.

**Comment by rowlandm** [comment]
[RSEAA063 now includes outreach information](https://docs.google.com/spreadsheets/d/1OciYM8uEPQlBNZoFfQSIAQhgEB49MaHiV-3iEtTidM8/edit#gid=1799203246)

**Comment by rowlandm** [comment]
Sent prospectus email to director.nci@anu.edu.au

**Comment by rowlandm** [comment]
Forgot to send prospectus - this is the compressed one.

[2023 RSE Asia Australia Prospectus.pdf](https://github.com/RSEAA/RSEAA.github.io/files/11639327/2023.RSE.Asia.Australia.Prospectus.pdf)

**Comment by rowlandm** [comment]
ugo.varetto@csiro.au

Hi Ugo,

I was wondering if you happened to know who the best person would be to reach out to about sponsoring the 2023 Research Software Engineer (RSE) Asia Australia Unconference?

I happen to be the Co-Chair and was hoping to reach out to the right person at Pawsey, but wasn't sure who that was. 

Would you be able to let me know who might be the best person for this please?

**Comment by rowlandm** [comment]
@SaranjeetKaur  - I will leave Society of RSE to you if you have time.

**Comment by rowlandm** [comment]
Philip Dart and Dougie Boyle UoM

Hi Dougie and Philip,

I am writing to you to offer a partnership opportunity for RSEAA2023.


As you may already know, the second online Research Software Engineer (RSE) Asia Australia Unconference (RSEAA2023) is scheduled from the 13th to the 15th of September 2023. This is a joint partnership between the RSE Asia Association and the RSE Australia New Zealand Association.


This is an event to ensure RSEs have a say on how they develop the community and to allow them to share their valuable technical and social knowledge of research software with the community. 


We contacted you because of your commitment to RSEs at the University of Melbourne and because we felt having a prominent university partnering with us would implicitly demonstrate the importance of RSEs within the research ecosystem.


Our 2022 unconference was a success as we had:

141 participants were registered for the unconference, 

17 different community-led sessions, and 

a maximum of 77 participants in one session.


By supporting us as a partner in 2023, you will be helping to raise awareness not only of your organisation, but of the importance and value of RSEs as a community and as individuals. This would be especially advantageous for organisations wanting to target a technology-savvy, multi-disciplinary audience that is relied on to provide advice for technology decisions.

 

You can find more information in our prospectus that is attached.


If you would like to support the community in other ways, you could share the details of the Unconference via your organisation’s mailing list and encourage attendance from any potential RSEs working for your organisation or people who work with RSEs.


Please let the organising committee know (rse2023@rse-aunz.org) if you would like to partner with us, or if you have any further ideas you can support the community, or if you have any comments or questions.


We appreciate any support you can provide!




Regards,

Rowland Mosbergen B Eng (Aerospace Avionics)
Co-Chair of the 2023 RSE Asia Australia Unconference
RCP Strategic Engagement and Planning Manager
Research Computing Platform

E mosbergen.r@wehi.edu.au
M +61 423 030 626

**Comment by rowlandm** [comment]
I was just about to write an email to Michelle Barker @SaranjeetKaur  - but maybe you are the best person to reach out ;)

**Comment by rowlandm** [comment]
I sent a lot of emails to Australian organisations. Now what about trans-international ones and Asian ones?

**Comment by rowlandm** [comment]
Yes from NCI

**Comment by SaranjeetKaur** [comment]
Sent to Michelle Barker from ReSA

**Comment by rowlandm** [comment]
Do we have suggestions for other organisations we could target @SaranjeetKaur @GraceAHall @sapkota-subash @kozo2 @pr4deepr ?

Remember that even if they said no, an email about this event might raise awareness for them that Research Software Engineering is a thing.

**Comment by pr4deepr** [comment]
Numfocus: https://numfocus.org/
Have gone about universities?

**Comment by rowlandm** [comment]
I've only reached out to UniMelb - but yes, that is a great idea @pr4deepr !!!

Maybe we could ask the community to fill out a form suggesting who we could reach out to at each university? Is that a good idea?

**Comment by rowlandm** [comment]
I'm also happy to do this for [NCRIS facilities too](https://www.education.gov.au/ncris).

**Comment by rowlandm** [comment]
ARDC signed as Key Partner, NCI said yes but has to decide, AARNet said yes but has to decide, QCIF signed as Allied Partner, BioCommons said yes but has to decide.

**Comment by rowlandm** [comment]
ARDC signed as Key Partner, NCI said yes to Allied partner, AARNet said yes to Allied Partner, QCIF signed as Allied Partner, BioCommons said yes but has to decide.

**Comment by rowlandm** [comment]
BioCommons said yes as a Key Partner.
