### ISSUE TITLE
Organise regular meetings

### ISSUE THREAD

**Issue by shyamaW** [RSEAA/RSEAA.github.io#10]

**Comment by SaranjeetKaur** [comment]
Perhaps go for fortnightly meetings after June?

**Comment by SaranjeetKaur** [comment]
@rowlandm - would set up recurring fortnightly meetings from June onwards and
@Emmanuel19-ada - would share reminders about the meetings

**Comment by SaranjeetKaur** [comment]
Maybe use Zoom?

**Comment by SaranjeetKaur** [comment]
@sapkota-subash could you please communicate with @Emmanuel19-ada for regular Zoom meetings?

**Comment by rowlandm** [comment]
I have [created a hackmd.io notepad for the 22nd of June meeting ](https://hackmd.io/@nsuDQSQzSSmnu6IZ_MyLew/rkCe27-wn)

**Comment by shyamaW** [comment]
Hi @Emmanuel19-ada @rowlandm @SaranjeetKaur @sapkota-subash 

Could you please share the next meeting link with calendar notifications? If you already shared it, could you please resend it to me again.

**Comment by rowlandm** [comment]
My office software doesn't handle notifications well. The calendar event was sent but with minimal notifications.
