### ISSUE TITLE
Handle scholarships, micro-grants, and posters

### ISSUE THREAD

**Issue by chrismpr86** [RSEAA/RSEAA.github.io#118]
@chrismpr86 can you please:

- [x] Respond to any scholarship /micro-grant applications at least twice a week, ideally as they come in
- [x] Ask for approval from @jyoti-bhogal and @rowlandm and cc in rse2024
- [x] Once approved, send out email that they are conditionally approved as they need to submit the poster
- [ ] Share with rse2024 if their poster is submitted to Zenodo - ask @richarddushime  for access 
- [ ] Review posters even from non-scholarship and non-micro-grant applicants on Zenodo
- [ ] Review the poster with @richarddushime and if they have shown some level of effort, then you can approve the poster
- [ ] Once poster is approved please update in a spreadsheet
- [ ] If micro-grant, please ask them to provide bank account details to financemanagement@we-are-ols.org - [see prevous years honorarium form](https://docs.google.com/forms/d/e/1FAIpQLSeT9aY-2FOmqVVHtG7kpEMwyJntsrh6ENkTBWymXREs-3WSKw/viewform).
- [ ] Followup with reporting to the committee weekly on this

**Comment by chrismpr86** [comment]
checked on 28/06/24-none yet

**Comment by richarddushime** [comment]
sent  notification status to the recent submission

**Comment by chrismpr86** [comment]
https://docs.google.com/spreadsheets/d/1cC8TEDHYoDOF6-AQ1Lpo406FX7VKnqEKNHjdolJaF-I/edit?gid=957484036#gid=957484036

**Comment by chrismpr86** [comment]
RSEAA2024 Honorarium Form: https://docs.google.com/forms/d/1evZtkdBe4VLsosjIYQJabcYfMNYpa3rBSLUGFLEd7fk/edit

**Comment by rowlandm** [comment]
For any honoraria you'd like to pay, please point people to our central honoraria form: https://openlifescience.civicrm.org/civicrm/honorarium They should pick the "Other option" from the drop down and use the "What task did you perform" option to indicate RSEAA24. A spreadsheet with the people and amounts approved by you would be most welcome and we can then easily process those requests. 

-- From Patricia at OLS.

**Comment by rowlandm** [comment]
Added information to [RSEAA24-011 Budget > Honorarium](https://docs.google.com/spreadsheets/d/1kcrzuK4vr8quQ5r7uBu7wHMIajfBwP3OyG_QiDHDMCA/edit?gid=1560430760#gid=1560430760)

**Comment by rowlandm** [comment]
Email with details of this has been sent to Patricia. This can now be closed. Great work everyone!
