### ISSUE TITLE
check with sponsors interested last year

### ISSUE THREAD

**Issue by SaranjeetKaur** [RSEAA/RSEAA.github.io#13]
Have sent an email to Oracle rep to check if they are still interested in sponsoring us this year. No response received yet.

**Comment by SaranjeetKaur** [comment]
Have to reach out to Society of RSE yet as they were accessibility partners last year

**Comment by SaranjeetKaur** [comment]
Email to Oracle (Richard):

-----------------------------
Dear Richard,

I am writing this email following our discussions at RSECon 2022 and subsequent interactions via email and again at the first joint RSE Asia Australia unconference in 2022 (online). 

I recall you had expressed an interest about how Oracle could support the efforts of the RSEng community in the Asia Pacific region. I am happy to share that we are planning another online unconference in September this year!

We are now looking for sponsors for this unconference and I want to discuss with you how Oracle could support us with that. 

I am CCing Rowland on this email who has been instrumental in organising this unconference.

Also attaching the prospectus for the RSEng Asia Australia Unconference 2023 along with this email for your reference.

Hope you are doing well!

Best,
Saranjeet

-----------------------------
Hi Richard,

Just checking if you have any thoughts on this. Also looping in Lei Li and Harinda on this email for their thoughts.

Best,
Saranjeet

**Comment by SaranjeetKaur** [comment]
Looks like Oracle is not much keen this year.

**Comment by rowlandm** [comment]
Ok we have reached out to ARDC, QCIF, NCI, Google Cloud - only one left is Society of RSE.
