### ISSUE TITLE
Review Registration Form details

### ISSUE THREAD

**Issue by shyamaW** [RSEAA/RSEAA.github.io#17]

**Comment by SaranjeetKaur** [comment]
@Emmanuel19-ada needs last year's registration form to develop on it

**Comment by SaranjeetKaur** [comment]
When do we start the registrations? (any date)

**Comment by rowlandm** [comment]
This is more of a second phase thing. Ideally I would like to finalise keynotes before registration opens. Maybe mid-July for registrations to open?
