### ISSUE TITLE
Create flyers based off last year

### ISSUE THREAD

**Issue by shyamaW** [RSEAA/RSEAA.github.io#19]

**Comment by rowlandm** [comment]
Added logos here - https://drive.google.com/drive/u/1/folders/1uvGvMC-tbeFne1L1wsg5pJtlyv3tKXXl

**Comment by rowlandm** [comment]
Added [RSEAA070 Flyers in canva](https://www.canva.com/design/DAFpI1X0Few/OdjWJhD_YtAB3gEJ_Ga9FA/view?utm_content=DAFpI1X0Few&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink)
