### ISSUE TITLE
Reach out to potential speakers ECR and Senior

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#2]

**Comment by rowlandm** [comment]
To boost accessibility, we should ask in our keynote email if there is a willingness for keynotes to provide an accessible slides along with their normal ones and a willingness to go through a 30 minute bootstrapping training session.

**Comment by rowlandm** [comment]
Speakers from RSE Asia for senior keynote, RSE Australia for junior keynote

**Comment by lessa-maker** [comment]
Good day, all, 
I hope this email finds you well, 
Please find attached an update of the email to be sent to potential speakers. 
could you have time to comment?
https://docs.google.com/document/d/1cg7qX_l9CKdQ57qUBQKbhsZUytFapUunBkIV47xuJnk/edit#


Best regards

LESSA TCHOHOU Fabrice, MSc.

Seed Industry / Seed Technology
YALI Alumni, Public Management
Secretary-General J2D-Afrique
+237 699 08 13 70 672 83 33 05 

    On Saturday, 13 May 2023 at 11:46:53 GMT+1, rowlandm ***@***.***> wrote:  
 
 


Assigned #2 to @lessa-maker.

**Comment by rowlandm** [comment]
Hi @lessa-maker this is for the senior panel. Do we have one for the ECR and Senior keynotes?

**Comment by SaranjeetKaur** [comment]
#RSEAA68 has lists for potentials speakers from last year

**Comment by SaranjeetKaur** [comment]
Check with the potential keynotes if they would be happy to provide accessible slides

**Comment by rowlandm** [comment]
[RSEAA069 Email template to send to potential speakers and panelists](https://docs.google.com/document/d/1l88LPnmgMTq-7nu_c6Yi051cJicLBd4D5ucPNwQxHi4/edit?usp=sharing)

This needs a clean up - can we work on this as well during this week please? @sapkota-subash @SaranjeetKaur @GraceAHall @kozo2 @pr4deepr @Emmanuel19-ada @lessa-maker @shyamaW

**Comment by rowlandm** [comment]
Some suggestions to spark discussion


Type | 1st Choice | 2nd Choice | 3rd Choice | 4th Choice | 5th Choice
-- | -- | -- | -- | -- | --
Junior keynote (Australia) | Kiowa | Sadia Waleem | Peiyu |   |  
Senior Keynote (Asia) |   |   |   |   |

**Comment by SaranjeetKaur** [comment]
Added a few names to senior keynote (Asia) on the google sheet

**Comment by rowlandm** [comment]
I have updated the [RSEAA069 Email template to send to potential speakers and panelists](https://docs.google.com/document/d/1l88LPnmgMTq-7nu_c6Yi051cJicLBd4D5ucPNwQxHi4/edit?usp=sharing) for the early career keynote.

**Comment by rowlandm** [comment]
I have updated the [RSEAA069 Email template to send to potential speakers and panelists](https://docs.google.com/document/d/1l88LPnmgMTq-7nu_c6Yi051cJicLBd4D5ucPNwQxHi4/edit?usp=sharing) for the mid career keynote as well.

**Comment by rowlandm** [comment]
[List of speakers is at RSEAA068](https://docs.google.com/spreadsheets/d/1ApxZ7q2TnSIGXv17zvb4jRKbcSY9DV0sChV0mHVqXrk/edit)

**Comment by rowlandm** [comment]
[9:34 a. m., 10/6/2023] RM: Hi All, if we are happy with the email templates for the ECR and MCR keynotes in RSEAA069 https://docs.google.com/document/d/1l88LPnmgMTq-7nu_c6Yi051cJicLBd4D5ucPNwQxHi4/edit?usp=sharing
[9:35 a. m., 10/6/2023] RM: And happy with the potential keynotes in priority order in RSEAA063 (in tab Suggested Speakers) https://docs.google.com/spreadsheets/d/1OciYM8uEPQlBNZoFfQSIAQhgEB49MaHiV-3iEtTidM8/edit#gid=0
[9:35 a. m., 10/6/2023] RM: We can start sending out the emails

**Comment by shyamaW** [comment]
Hi All @rowlandm @SaranjeetKaur @lessa-maker @kozo2 @pr4deepr 

I also went through the templates. I am happy with the templates. However, Before sending, I think, we need to check and add the corrected dates (if I am not wrong). Moreover, the new website links also be added

**Comment by rowlandm** [comment]
Sent email to Draga for junior keynote. 

- @SaranjeetKaur  are you OK sending an invitation to the senior RSE keynote (or delegating it)?
- @SaranjeetKaur are you OK sending an invitation to the RSE Asia representative Anelda or delegating?
- @SaranjeetKaur are you OK sending an invitation to the Asian Senior Rep Professor Rahman or delegating?

**Comment by rowlandm** [comment]
Draga said no for junior keynote.

**Comment by rowlandm** [comment]
Sadia is actually a senior RSE now..... How time flies....

But I don't think she would be a good fit for the junior RSE keynote now...
