### ISSUE TITLE
Some resources on making accessible presentations

### ISSUE THREAD

**Issue by SaranjeetKaur** [RSEAA/RSEAA.github.io#28]
From useR 2021 conference: https://user2021.r-project.org/blog/2021/12/07/accessibility_awards_interview/

**Comment by SaranjeetKaur** [comment]
@rowlandm - this is the resource I mentioned about on your point of making accessible presentations

**Comment by shyamaW** [comment]
@rowlandm @SaranjeetKaur Gentle Reminder! I hope you are working on this task—anything to be updated?

**Comment by rowlandm** [comment]
I haven't moved this forward yet. But I would like to add something into the email template about it.

**Comment by shyamaW** [comment]
@rowlandm 

Have you finalized/identified the resources for making accessible presentations?

How we are going to create accessible presentations?

**Comment by rowlandm** [comment]
I will record a session of me setting up a more accessible presentation, hopefully with the speakers.

This will happen once we get keynotes accepted.

**Comment by rowlandm** [comment]
Just use the work Liz provided last year - https://rse-aunz.github.io/RSEAUNZAccessibility.html#accessibility-standards-for-presenters

And I might make some of my own suggestions to the two keynotes.

**Comment by rowlandm** [comment]
Accessibility suggestions for your keynote at RSE Asia Australia Unconference 2023

Dear Professor Ginige,

Thank you again for agreeing to keynote for us at the RSE Asia Australia Unconference 2023!

You will be speaking on the 14th September 2023 at 1.30pm UTC+10 ([link to your time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230914T0330)). The theme for the unconference will be "Silos to Synergy - Achieving collaboration across domains".


Last year we asked Liz Hare to help us improve the accessibility for the conference and she wrote this on [how speakers can make their presentations more accessible](https://rse-aunz.github.io/RSEAUNZAccessibility.html#accessibility-standards-for-presenters).

We encourage you to read this and take some of her suggestions on board.

I am also able to meet with you for 30 minutes to show how I have adapted my presentations to make them more accessible too. This is [an example of a presentation](https://figshare.com/articles/presentation/Three_Common_Mistakes_in_Managing_Complex_New_Projects/23639565) where I wrote an accessible version of my presentation first before creating a less accessible version. I then try to distribute this to the audience before the day of the presentation.

Please let us know if you have any comments or questions.
