### ISSUE TITLE
Choose a theme for RSEAA23

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#29]

**Comment by rowlandm** [comment]
Choose a theme - I would like Working together, or sharing knowledge, or projects that go across domains

**Comment by rowlandm** [comment]
eg. How can we find projects that will help RSEs across multiple domains (eg. Imaging, Ecology, HASS, STEM etc) or singular projects that can help show that RSEs are valuable across domains?

**Comment by pr4deepr** [comment]
From Silos to Synergy ?
Building Bridges?
Cultivating collaborative networks?

**Comment by rowlandm** [comment]
I like silos to synergy!

**Comment by rowlandm** [comment]
"Silos to Synergy - Achieving collaboration across domains" will be our theme for RSEA2023
