### ISSUE TITLE
Reach out to potential senior panelists

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#3]

**Comment by rowlandm** [comment]
Want to ask them about senior advisory group as well - build this into panel?

**Comment by rowlandm** [comment]
HI @SaranjeetKaur  - I would like to invite Professor Jung Sun Kim as the senior panelist for Asia first. Is that OK? She was the most interested when we asked her last year and it would be nice to reach out to her again.

**Comment by rowlandm** [comment]
@SaranjeetKaur and I was thinking of Michelle Barker for Australia senior panel. What do you think?

**Comment by rowlandm** [comment]
[RSEAA069 Email template to send to potential speakers and panelists](https://docs.google.com/document/d/1l88LPnmgMTq-7nu_c6Yi051cJicLBd4D5ucPNwQxHi4/edit?usp=sharing)

This needs a clean up for senior panelists too - can we work on this as well during this week please? @SaranjeetKaur

**Comment by rowlandm** [comment]
Initial suggestions based off 2022 and my own network....


Area | Type | Role | 1st Choice | 2nd Choice | 3rd Choice | 4th Choice | 5th Choice
-- | -- | -- | -- | -- | -- | -- | --
Asia | Panel | RSE Asia rep | Jyoti Bhogal | Saranjeet |   |   |  
AU | Panel | RSE Oz rep | Manodeep | Rowland |   |   |  
AU | Panel | Senior AU Rep | Prof Liz Sonenberg | Prof Johnston-Hollitt | Rosie ARDC | Tony Papenfuss | Dougie Boyle
Asia | Panel | Senior Asia Rep | Prof Jung Sun Kim | Prof Sanghamitra Bandyopadhyay | Damayanti Buchori | Kayo Inaba | Yookyoung Mun
NZ | Panel | Chair | Nooriyah | Michelle Barker | Georgina Rae |   |

**Comment by rowlandm** [comment]
Liz Sonenberg said no.
Next - is Prof Johnston-Hollitt.

**Comment by rowlandm** [comment]
Sent to Prof Johnston-Hollitt.

**Comment by rowlandm** [comment]
Prof Johnston-Hollitt accepted!

**Comment by SaranjeetKaur** [comment]
Also Manodeep has accepted!

**Comment by rowlandm** [comment]
Nooriyah accepted as facilitator!

**Comment by rowlandm** [comment]
All panelists have been finalised.
