### ISSUE TITLE
About promoting the unconference

### ISSUE THREAD

**Issue by SaranjeetKaur** [RSEAA/RSEAA.github.io#31]
Hi folks,

Want to bring to your notice this project by Alex Coleman, who is attempting to host a website that lists all upcoming RSE events: https://sparrow0hawk.github.io/rse-calendar/

I thought when we have the registrations open for the unconference and want it promote it, it would be nice to include it on this website either by submitting a pull request or using a GitHub issue: https://github.com/Sparrow0hawk/rse-calendar#contributing-an-event-to-the-calendar

(I have got some events submitted and it only takes a few minutes to do so - so I am happy to take this up during the promotion stage.).

Best,
Saranjeet

Rowland Mosbergen |   | Mon, Jun 26, 5:32 PM (1 day ago)

Great idea!

Someone also shared this list of resources on RSE Asia's Twitter handle and it has links to RSE Conferences too: https://github.com/hifis-net/awesome-rse-science. Dropping it here so that it all stays in one place to be able to come back to!

Best,
Saranjeet

**Comment by rowlandm** [comment]
[RSEAA075 Communications Plan](https://docs.google.com/spreadsheets/d/1hioHMgh1xxeni6GKmGzBzB6uDb1dzQShYoOsRv5XERo/edit#gid=0)

[Marketing Material](https://rseaa.github.io/marketing)
