### ISSUE TITLE
AskMeAnything for the Unconference

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#48]

**Comment by rowlandm** [comment]
This could be a time to ask about sessions, posters, scholarships etc.

**Comment by dewoller** [comment]
I'm guessing this was a few weeks back

**Comment by rowlandm** [comment]
We were doing it on Thursdays at 4pm Melbourne time (UTC +11) but my daughter got sick and I've been on carers leave since then
