### ISSUE TITLE
Setup Virtual Booths for Key Partners

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#49]

**Comment by rowlandm** [comment]
We want to create a Virtual Booth for Australian BioCommons and ARDC.

This allows them to setup a "Booth" for the conference.

[Zoom Events has some tutorials](https://support.zoom.us/hc/en-us/articles/4420629099917-Managing-Zoom-Events-expo).

**Comment by rowlandm** [comment]
I can reach out to the key partners once someone else has set it up for them.

**Comment by rowlandm** [comment]
You can access the event by this link

https://events.zoom.us/e/event/setup/vyNMCoqNS32PetApN6iRjw/overview

**Comment by richarddushime** [comment]
i  facing the following error " Something went wrong. Please go to Zoom Customer Support to report the issue " 
while  setting the expo

**Comment by rowlandm** [comment]
I may not have given you access.

Let me see if I can add it

**Comment by richarddushime** [comment]
Alright , Thanks

**Comment by rowlandm** [comment]
OK - you should have more access now.

**Comment by richarddushime** [comment]
> We want to create a Virtual Booth for Australian BioCommons and ARDC.
> 
> This allows them to setup a "Booth" for the conference.
> 
> [Zoom Events has some tutorials](https://support.zoom.us/hc/en-us/articles/4420629099917-Managing-Zoom-Events-expo).

I m working on this  and i will need the point of contact for the 2 key partners , 
while creating an exhibitor its mandatory fields 
Name and email

**Comment by richarddushime** [comment]
Hi @rowlandm @SaranjeetKaur 
i did set up the virtual booth for ARDC  tomorrow i will be setting up for Biocommons
i m inquiring for a check in

**Comment by SaranjeetKaur** [comment]
Thanks Richard! I've dropped an email to Christina - hopefully they will
reply soon.
