### ISSUE TITLE
Setup website page similar to last year / setup new rseaa.github.io website

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#5]

**Comment by rowlandm** [comment]
I think we should have the front page of rseaa.github.io be the 2023 version on one page.

**Comment by rowlandm** [comment]
https://rseaa.github.io/

**Comment by shyamaW** [comment]
Hi @rowlandm Reminder! 
is this a similar task to issue #7? Then shall we remove this task from our list?

**Comment by rowlandm** [comment]
Could we ask @pr4deepr , @lessa-maker , @Emmanuel19-ada to see if there could make the https://rseaa.github.io/ nicer?

It would be nice to have the title colour change and the ability to have a  logo at the top like https://rse-aunz.github.io/

**Comment by pr4deepr** [comment]
Is adding a theme part of it?
for example, from here: https://pages.github.com/themes/ 
?

**Comment by rowlandm** [comment]
Yes, although I think they had to custom a theme to get what they wanted ..

**Comment by pr4deepr** [comment]
I had a go at the layout, can you look at it now?

**Comment by rowlandm** [comment]
That looks great!

I will check it how I can change the title and stuff.

Thanks!
