### ISSUE TITLE
Budget for RSEAA24

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#68]
Rough budgeting to get started and to add extras.

[Full budget to get pre-approved from OLS and SC](https://docs.google.com/spreadsheets/d/1kcrzuK4vr8quQ5r7uBu7wHMIajfBwP3OyG_QiDHDMCA/edit?usp=sharing).

**Comment by rowlandm** [comment]
Look at potential budget to start: $3000 AUD

- Secretary $2000
- 3 x organising committee $250 each
- Zoom Pro One $250 

Extras can include:

- RedBee Media transcripts $1000
- Accessibility mini-grants $50 each up to $500
- $100 for each speaker and senior panelist

**Comment by rowlandm** [comment]
Ask Saranjeet if we can kickstart RSEAA24 (initial $3000) by using the shared money in QCIF trust. This will be split 50/50 $1500 from RSEAUNZ and $1500 from RSE Asia.

**Comment by rowlandm** [comment]
use figshare and github discussions once again - they are free.

**Comment by rowlandm** [comment]
Could also see if we can use YouTube live so it gets recorded straight away. I'm happy if others are happy to use it. Might be too open. Maybe we could trial it with one - like the senior panel or the opening keynote.

**Comment by rowlandm** [comment]
Ask Philip to see if he can get students to build a full working admin system to streamline processes.

**Comment by rowlandm** [comment]
Maybe $1600 secretary
$200 each committee member X3
$700 budget speakers etc
$300 zoom pro one

**Comment by rowlandm** [comment]
Extra $1000 for secretary to run the event

**Comment by rowlandm** [comment]
Sent email to rse2024 / steering committee for FYI.

**Comment by rowlandm** [comment]
Ask steering committee if they could pre-approve budget for OLS - would this work?

**Comment by richarddushime** [comment]
> Could also see if we can use YouTube live so it gets recorded straight away. I'm happy if others are happy to use it. Might be too open. Maybe we could trial it with one - like the senior panel or the opening keynote.

Just a Quick Reminder 
Do we still have the YouTube account Accessible ? for RSEAA

**Comment by rowlandm** [comment]
Adding "Do we still have the YouTube account Accessible ? for RSEAA" to a new task. Closing out as Richard gives his OK too.
