### ISSUE TITLE
Setup website page similar to last year

### ISSUE THREAD

**Issue by shyamaW** [RSEAA/RSEAA.github.io#7]
Add prospectus to the new web page.

**Comment by SaranjeetKaur** [comment]
https://rse-aunz.github.io/2023-Asia-Australia-unconference/

**Comment by SaranjeetKaur** [comment]
@pr4deepr any updates on this?

**Comment by rowlandm** [comment]
Hi @pr4deepr - I don't think you saw but we actually created a new website for the long term at https://rseaa.github.io/

I think this item being still "in progress" was for discussing if we have the time to migrate to this website or wait until next year. Sorry - I didn't put this in the issue before....

My gut feeling is that we wait until we have the time, or we ask the community to help us...

**Comment by pr4deepr** [comment]
Can I get access to the repository. I can try migrating it to this...

**Comment by pr4deepr** [comment]
Thanks, have access now.. Prospectus uploaded
https://github.com/RSEAA/RSEAA.github.io/commit/954b06bc08d56f190ecc969a1bd60360774b404b
