### ISSUE TITLE
Create posters and topics for RSEAA24

### ISSUE THREAD

**Issue by richarddushime** [RSEAA/RSEAA.github.io#77]
This year's discussions can be found here 
[RSEAA24 Discussion Topics and Posters](https://github.com/RSEAA/RSEAA.github.io/discussions?discussions_q=is%3Aopen+label%3ARSEAA24)

last year  discussions 
[RSEAA23 ](https://github.com/RSEAA/RSEAA.github.io/discussions)

**Comment by richarddushime** [comment]
As a collaborator, i m not  be able to add the  discussion and poster welcome message to the announcement category , 
you could help in adding them to the announcements category 

Additionnallly I created a label for RSEAA24  This will help in always identifying this years posters and discussions easily

**Comment by richarddushime** [comment]
i will rework on it again later

**Comment by rowlandm** [comment]
Thank you!

**Comment by rowlandm** [comment]
Figshare Project vs Zenodo Community for posters

I prefer Zenodo because with Figshare you create a project and invite users. With Zenodo you create a community and someone can submit a draft for you to review.

https://help.figshare.com/article/how-to-use-projects-and-collaborate-on-figshare

https://help.zenodo.org/docs/share/submit-for-review/

**Comment by richarddushime** [comment]
> Figshare Project vs Zenodo Community for posters
> 
> I prefer Zenodo because with Figshare you create a project and invite users. With Zenodo you create a community and someone can submit a draft for you to review.
> 
> https://help.figshare.com/article/how-to-use-projects-and-collaborate-on-figshare
> 
> https://help.zenodo.org/docs/share/submit-for-review/
> 
> These are [the Zenodo instructions for Collaborations Workshop SSI 2024](https://zenodo.org/records/10848451)

would you create an RSEAA community on Zenodo and add me in, so that I proceed with updating the instructions?

**Comment by rowlandm** [comment]
Yes, I will do this tomorrow. Cheers!

**Comment by rowlandm** [comment]
Done. You can see it at
https://zenodo.org/communities/rseaa/records?q=&l=list&p=1&s=10

But you need to create an account and then Users must set profile
visibility to "Public" in order to be invited to a community.

**Comment by richarddushime** [comment]
[RSEAA24 Zenodo Submission Guide ](https://zenodo.org/records/10937721?token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6IjVhNzJmNWY3LTBkZjYtNGE1Yy05Y2JiLWI1Yjg0Yzk0MGJiNCIsImRhdGEiOnt9LCJyYW5kb20iOiIwZWNhMWRjYzk1ZmFhNzMxYzU2ZWM0MGFlN2EzZTkxNiJ9.Ge7Lz2-NUQ-XAAb5rFjcuYhcPFq0aTOnvAoz9AeNnj93W555DrLxjA1gPWNLl7qZfhmtGn0q9314oSeGVb4oMg   
)


shortenered url  [https://rb.gy/7cl10g](https://rb.gy/7cl10g)
