### ISSUE TITLE
Create slack channel similar to CW24?

### ISSUE THREAD

**Issue by rowlandm** [RSEAA/RSEAA.github.io#87]
from CW24 email

Engagement Pathways

Please join the CW24 Slack workspace, where you will be able to connect with other participants and receive any updates from the organisers. (Please do not share this link publicly, as it is for re gistered participants only and we want to maintain a safe environment.)

We will be using Google Documents for collaborative note-taking and keeping everyone synchronised during CW24. The links to these documents will be shared with participants on the day, although participants should feel empowered to use their preferred collaboration tools during the group sessions.

**Comment by richarddushime** [comment]
We will create  a slack channel almost to the event after closing registration 
my suggestion

**Comment by rowlandm** [comment]
Just want to say that timing the creation of the Slack space a few days before the workshop, so that the 14 days Pro trial covers it and a few days after, is ingenious :sonrisa:


From CW24

**Comment by rowlandm** [comment]
It could be even closer to the event as per the CW24 post.

**Comment by richarddushime** [comment]
made a small PR to add this on the suggested schedule  in the last 1 week

**Comment by rowlandm** [comment]
Will close this.
