### ISSUE TITLE
Check where we can get a website domain and email

### ISSUE THREAD

**Issue by chrismpr86** [RSEAA/RSEAA.github.io#89]
To access:
Website domain, Emails and re-direct to main domain

**Comment by chrismpr86** [comment]
https://dreamithost.com.au/domains

**Comment by rowlandm** [comment]
RSE-AUNZ is registered through cloudflare - which is just about the cheapest domain registrar available (~ 7.50 USD/year). Did you already have an org account for RSEAA on GitHub? Basically with a GitHub org and cloudflare, I know how to setup the static pages and serve it through the domain (without paying for another hosting service - which is how we do it for RSE-AUNZ). From Manodeep.

**Comment by richarddushime** [comment]
@rowlandm Did you manage to work on  the info@rseaa.org  mail ? to mark this Done

**Comment by rowlandm** [comment]
No, it will have to be done on the weekend

**Comment by rowlandm** [comment]
Decided to leave rse2024@rse-aunz.org as is as info@rseaa.org has a little more complications.

I could have:
- used forwardemail.net or
- used my own hosting to setup

But I didn't want to change any of the DNS settings for CloudFlare.

**Comment by richarddushime** [comment]
Alright 
For the future again
