### ISSUE TITLE
Calculate budget needed to improve accessibility report

### ISSUE THREAD

**Issue by shyamaW** [RSEAA/RSEAA.github.io#9]

**Comment by SaranjeetKaur** [comment]
Is it ok to reserve the same budget like last year (which was utilised to compensate Liz for their work on the report)?

**Comment by rowlandm** [comment]
I think making it $1000 AUD would be a minimum. Then on top of that is really about the transcripts for the 2 x keynotes - maybe another $250 AUD each - so maybe $1500 AUD?

**Comment by rowlandm** [comment]
What is the cost for transcripts for the keynotes - somethign to find out.
