### ISSUE TITLE
Check alternatives for Eventbrite

### ISSUE THREAD

**Issue by chrismpr86** [RSEAA/RSEAA.github.io#90]
Check this report: https://rseaa.github.io/RSEAUNZAccessibility.html

**Comment by richarddushime** [comment]
Alternatives for  eventbright 

We could look into the below 
1. [Meetup](https://www.meetup.com/)
2. [Ticket Tailor](https://www.tickettailor.com/)
3. [cvent](https://www.cvent.com/)
4. [Regfox](https://www.regfox.com/)

Based on the  accessibility report 

We can choose in the above 
looking at factors like 
pricing and features

**Comment by rowlandm** [comment]
How did you choose these? I only saw conftool in the report.

It is difficult to test accessibility unless you test with a screen reader.

**Comment by rowlandm** [comment]
https://www.conftool.net/en/index.html

**Comment by richarddushime** [comment]
based on the information provided on the website and easy to use 

The conftool  i did not also test anything  and i have not used it  unless ticket tailor  ( a friend is using it )

i will request for demos for  the few  then i will judge from there

**Comment by rowlandm** [comment]
You can't really test for accessibility of you don't use a screen reader.

Let's chat about this tomorrow.

**Comment by rowlandm** [comment]
@richarddushime @chrismpr86  - I'm happy to use [Humanitix](https://humanitix.com/au). Can we go with this solution please?

The main reason is that [Vision Australia](https://www.visionaustralia.org/) uses them. They are the leading national provider of personalised technology, services and information for anyone experiencing or supporting those with vision loss. If they are using Humanitix, then it must be OK.

- https://events.humanitix.com/host/5c48fdf213671d000f56a382
- https://humanitix.com/us/blog/accessibility

**Comment by richarddushime** [comment]
Sounds Great 
Not sure How i did not think of it 
We good to use it

**Comment by rowlandm** [comment]
Humanitix - no alt-text for banner
Your fee structure:
Booking fee: 4% + $0.99

**Comment by rowlandm** [comment]
[Link to test RSEAA24 on Humanitix](https://console.humanitix.com/console/my-events/6663a15f096e65b6f7c22fcf/info/basics)

**Comment by richarddushime** [comment]
Can you add us on the account for Humanitix ? 
Does it provide the option ?

**Comment by rowlandm** [comment]
We are just using it for testing for now. If we get good feedback I will
share details. The login email is ***@***.***

**Comment by richarddushime** [comment]
Here are the suggestions that I would like to make about the event page URL 
we could rename it from https://events.humanitix.com/rse-asia-australia-2024-rseaa24-lttp4775 to 
https://events.humanitix.com/rse-asia-australia-2024-rseaa24 ?
or any suggestions ? 
@rowlandm @chrismpr86 
Note that Editing the URL is possible

**Comment by richarddushime** [comment]
I would also like to confirm about the Checkout questions
Preview and let me know 
Thanks

**Comment by rowlandm** [comment]
I made some slight changes. Good to go at 12pm today Melbourne time.

I will send an email to rseaunz. Richard, can you send out posts on Twitter
and LinkedIn. I will copy this for Mastodon.

**Comment by richarddushime** [comment]
Done

**Comment by rowlandm** [comment]
We went with humanitix.
