### ISSUE TITLE
Adding key dates on the website

### ISSUE THREAD

**Issue by chrismpr86** [RSEAA/RSEAA.github.io#98]

**Comment by chrismpr86** [comment]
[Key Dates unconference.docx](https://github.com/user-attachments/files/15511726/Key.Dates.unconference.docx)

of discussion topic submissions

**Comment by rowlandm** [comment]
Key Dates
Registration and application dates
    • 19th June 12pm UTC +10 (Thursday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Micro-grant+application+due+date&iso=20230831T17&p1=3912)) - start of registration and scholarships and microgrants applications
    • 17th July 12pm UTC +10 (Thursday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Micro-grant+application+due+date&iso=20230831T17&p1=3912)) - end of scholarship and micro-grant applications
    • 14th August 12pm UTC +10 (Thursday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Micro-grant+application+due+date&iso=20230831T17&p1=3912)) - end of poster submission for eligible scholarship and micro-grant applicants and end of early bird registration
    • 6th September 12pm UTC +10 (Wednesday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Unconference+Registrations+and+Scholarships+Application+due+date&iso=20230906T17&p1=3912)) – end of registration
Event dates
    • 10th September 12:30pm UTC +10 (Wednesday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Unconference+Registrations+and+Scholarships+Application+due+date&iso=20230906T17&p1=3912)) - Leaders forum
    • 11th September 12:30pm UTC + 10 (Wednesday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Unconference+Day+1+Start&iso=20230913T1230&p1=3912)) - start of Day 1 of the unconference
    • 12th September 12:30pm UTC + 10 (Thursday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Unconference+Day+2+Start&iso=20230914T1230&p1=3912)) - start of Day 2 of the unconference
    • 13th September 12:30pm UTC +10 (Thursday) ([see in your time zone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Discussion+topic+submission+due+date&iso=20230914T14&p1=3912)) – start of day 3 and end of discussion topic submissions
